config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoice_temps
  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
    end 
  end 
  resources :categories
  resources :sectors
  resources :suppliers
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  root "home#index"
end

app/models/cart_temp.rb
class CartTemp < ApplicationRecord
  belongs_to :item
  validates :quantity, presence: true, comparison: { greater_than_or_equal_to: 1 } 

  
  def self.total_cost 
    CartTemp.joins("JOIN items ON items.id = cart_temps.item_id")
            .sum("price*cart_temps.quantity")
  end

  # SELECT sum(price) FROM cart_temps
	# JOIN items ON items.id = cart_temps.item_id;
end

app/controllers/cart_temps_controller.rb
class CartTempsController < ApplicationController
  before_action :set_cart_temp, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  include CartTempsConcerns

  #rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /cart_temps or /cart_temps.json
  def index
    @cart_temps = CartTemp.all
    @total_cost = CartTemp.total_cost
  end

  # GET /cart_temps/1 or /cart_temps/1.json
  def show
  end

  # GET /cart_temps/new
  def new
    @cart_temp = CartTemp.new
  end

  # GET /cart_temps/1/edit
  def edit
  end

  # POST /cart_temps or /cart_temps.json
  def create
    
    @cart_temp = CartTemp.new(cart_temp_params)
    item_exist = CartTemp.find_by(item_id: @cart_temp.item_id)
    item = Item.find(@cart_temp.item_id)

    respond_to do |format|
      if item_exist
        format.html { redirect_to add_cart_items_url, alert: "The item #{item.description} just exit in cart." }
      elsif @cart_temp.quantity <= 0
        format.html { redirect_to add_cart_items_url, alert: "The number of items must be greater than or equal to 1." }
      elsif  @cart_temp.quantity > item.quantity 
        format.html { redirect_to add_cart_items_url, alert: "The quantity of the chosen item must be less than the quantity saved." }
      elsif @cart_temp.save
          
        item.quantity = item.quantity - @cart_temp.quantity   
        item.update(item.as_json)
        format.html { redirect_to add_cart_items_url, notice: "Cart temp was successfully created." }
        format.json { render :show, status: :created, location: @cart_temp }
      else
        format.html { render new, status: :unprocessable_entity }
        format.json { render json: @cart_temp.errors, status: :unprocessable_entity }
      end
    end
  
  end

  # GET /cart_temps/:id/add_one_item
  def add_one_item
    item_in_cart = CartTemp.find(params[:id])
    item = Item.find(item_in_cart.item_id) 
    
    respond_to do |format|
      if item_out_of_stock?(item) # Item esgotado do stock
        format.html { redirect_to cart_temps_url, alert: "Item out of stock" }
      else
        item_in_cart.quantity += 1
        item_in_cart.update(item_in_cart.as_json)
        item.quantity = item.quantity - 1  
        item.update(item.as_json)

        format.html { redirect_to cart_temps_url, notice: "Cart temp was successfully created." }
        format.json { render :show, status: :created, location: @cart_temp } 
      end
    end
  end


  # GET /cart_temps/:id/add_one_item
  def remove_one_item
    item_in_cart = CartTemp.find(params[:id])
    item = Item.find(item_in_cart.item_id) 
    
    respond_to do |format|
      if item_out_of_stock?(item) # Item esgotado do stock
        format.html { redirect_to cart_temps_url, alert: "Item out of stock" }
      else
        item_in_cart.quantity -= 1
        item_in_cart.update(item_in_cart.as_json)
        item.quantity = item.quantity + 1  
        item.update(item.as_json)

        format.html { redirect_to cart_temps_url, notice: "Cart temp was successfully created." }
        format.json { render :show, status: :created, location: @cart_temp } 
      end
    end
  end

  def cart_abandoned
    @cart_temps = CartTemp.where(abandoned: true)
  end
  # PATCH/PUT /cart_temps/1 or /cart_temps/1.json
  def update
    respond_to do |format|
      if @cart_temp.update(cart_temp_params)
        format.html { redirect_to cart_temp_url(@cart_temp), notice: "Cart temp was successfully updated." }
        format.json { render :show, status: :ok, location: @cart_temp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart_temp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_temps/1 or /cart_temps/1.json
  def destroy
    item = Item.find(@cart_temp.item_id)

    item.quantity = item.quantity + @cart_temp.quantity   

    item.update(item.as_json)
    @cart_temp.destroy

    respond_to do |format|
      format.html { redirect_to cart_temps_url, notice: "Cart temp was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_temp
      @cart_temp = CartTemp.find(params[:id])
    end

    def invalid_cart
      logger.error "Invalid cart #{params[:id]}"
      redirect_to cart_temps_url, info: "Invalid cart."
    end

    # Only allow a list of trusted parameters through.
    def cart_temp_params
      params.require(:cart_temp).permit(:quantity, :abandoned, :item_id)
    end
end

app/helpers/cart_temps_helper.rb
module CartTempsHelper
end

app/views/cart_temps/_cart_temp.html.erb
  <tr>
    <div id="<%= dom_id cart_temp %>">
      <th scope="row"><%= cart_temp.item.item_code %></th>
      <td scope="col"><%= cart_temp.item.description %></td>
      <td scope="col"><%= cart_temp.quantity %></td>
      <td scope="col"><%= cart_temp.item.price %></td>
      <td scope="col"><%= cart_temp.item.price * cart_temp.quantity %></td>
      <td scope="col"><%= cart_temp.item.category.name_category %></td>
      <td scope="col"><%= cart_temp.item.sector.name_sector %></td>
      <td scope="col"><%= cart_temp.item.price + cart_temp.item.profite_value%></td>
      <td scope="col"><%= cart_temp.item.profite_value %></td>
      <td scope="col"><%= cart_temp.item.expiration_date %></td>
      <% if cart_temp.abandoned %>
         <td scope="col" class="text-success"><%= cart_temp.abandoned %></td>
      <% else %>
        <td scope="col" class="text-danger"><%= cart_temp.abandoned %></td>
      <% end %>

      <td>
        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
          <%= link_to "+", add_one_item_cart_temp_path(cart_temp), class:"btn btn-info" %>
          <%= link_to "-", remove_one_item_cart_temp_path(cart_temp), class:"btn btn-warning" %> 
        </div>
      </td>
           <td>
        <%= button_to "Delete", cart_temp, method: :delete, class:"btn btn-danger" %>
      </td>
    </div>
  </tr>

app/views/cart_temps/_form.html.erb
<%=form_with(model: cart_temp) do |form| %>
  <% if cart_temp.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cart_temp.errors.count, "error") %> prohibited this cart_temp from being saved:</h2>

      <ul>
        <% cart_temp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.number_field :quantity %>
    <%= form.hidden_field :abandoned %>
    <%= form.hidden_field :item_id %>

    <div class="mb-3 d-grid gap-2">
      <%= form.submit class: "btn btn-info" %>
    </div>
<% end %>

app/views/cart_temps/_form_add_one_item.html.erb
<%=form_with cart_temp, url: "/cart_temps/add_one_item", method: :post do |form| %>
  
    <%= form.hidden_field :id, value: cart_temp.id %>

  <%= form.submit "+", class:"btn btn-info add_item" %>
<% end %>

app/views/cart_temps/edit.html.erb
<h1>Editing cart temp</h1>

<%= render "form", cart_temp: @cart_temp %>

<br>

<div>
  <%= link_to "Show this cart temp", @cart_temp %> |
  <%= link_to "Back to cart temps", cart_temps_path %>
</div>

app/views/cart_temps/index.html.erb
  <section>
    <h5 class="fs-3 text-center">sales panel</h5>
    <div class="row">
      <div class="col-sm-4 fs-4 text-success">
        <strong>Total:</strong> <span class="total"><%=  @total_cost %></span> 
        <br/>
        <br/>
      </div>
      <div class="col">

      </div>
      <div class="col">

      </div>

    </div>
    <div class="d-grid gap-2 my-1">
        <%= link_to "Generate invoice", new_invoice_temp_path, class: "btn btn-success"%> 
    </div>

    <table class="table table-hover shadow-sm">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome/Descrição</th>
            <th scope="col">Q.Stock</th>
            <th scope="col">P.Unitário</th>
            <th scope="col">Sub.Total</th>
            <th scope="col">Categoria</th>
            <th scope="col">Sector</th>
            <th scope="col">V.Pagar</th>
            <th scope="col">Lucro</th>
            <th scope="col">D.Expiracao</th>
            <th scope="col">Abandoned</th>
            <th scope="col">Acrescentar</th>
            <th scope="col">Diminuir</th>
          </tr>
        </thead>
        <tbody>
          <div id="cart_temps">
            <% @cart_temps.each do |cart_temp| %>
              <%= render cart_temp %>
            <% end %>
          </div>
        </tbody>
      </table>

  </section>

  <!-- Fim Itens index-->

app/views/cart_temps/new.html.erb
<h1>New cart temp</h1>

<%= render "form", cart_temp: @cart_temp %>

<br>

<div>
  <%= link_to "Back to cart temps", cart_temps_path %>
</div>

app/views/cart_temps/show.html.erb
  <section>
    <h5 class="fs-3 text-center">sales panel</h5>

    <div class="d-grid gap-2 my-1">
        <%= link_to "Continuar com a venda", cart_temps_path, class: "btn btn-warning"%> 
    </div>

    <table class="table table-hover shadow-sm">
        <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome/Descrição</th>
            <th scope="col">Q.Stock</th>
            <th scope="col">P.Unitário</th>
            <th scope="col">Sub.Total</th>
            <th scope="col">Categoria</th>
            <th scope="col">Sector</th>
            <th scope="col">V.Pagar</th>
            <th scope="col">Lucro</th>
            <th scope="col">D.Expiracao</th>
            <th scope="col">Abandoned</th>
            <th scope="col"></th>
            
          </tr>
        </thead>
        <tbody>
          <div id="cart_temps">
            <%= render @cart_temp %>
          </div>
        </tbody>
      </table>

  </section>

  <!-- Fim Itens index-->