config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoice_temps
  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
    end 
  end 
  resources :categories
  resources :sectors
  resources :suppliers
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  root "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  
  has_one :profile, dependent: :destroy
  has_one :supplier, dependent: :destroy
  has_one :company

  validates_presence_of :street, :city
end

app/models/cart_historic.rb
class CartHistoric < ApplicationRecord
  belongs_to :item
  has_many :invoice_temps

end

app/models/cart_temp.rb
class CartTemp < ApplicationRecord
  belongs_to :item
  validates :quantity, presence: true, comparison: { greater_than_or_equal_to: 1 } 

  
  def self.total_cost 
    CartTemp.joins("JOIN items ON items.id = cart_temps.item_id")
            .sum("price*cart_temps.quantity")
  end

  # SELECT sum(price) FROM cart_temps
	# JOIN items ON items.id = cart_temps.item_id;
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  has_many :address
  
  validates_presence_of :province, :city_name

  scope :find_cities, ->(province) { where(province_id: province.id)}
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_one_attached :image
end

app/models/invoice_temp.rb
class InvoiceTemp < ApplicationRecord
  belongs_to :profile
  belongs_to :cart_historic
 
  enum payment_method: { monetario: "MASCULINO", transferencia: "FEMININO", cartao_de_debito: "CARTAO_DEBITO"}

  def self.find_by_cart_historic(cart_historic)  
    InvoiceTemp.joins(:cart_historic)
              .where("cart_historics.code_cart = #{cart_historic.code_cart}")
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :supplier
  belongs_to :category
  belongs_to :profile
  belongs_to :sector

  has_many :cart_temps
  has_many :cart_historics

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :items
  has_many :invoice_temps

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [140, 140]
  end

  validates_presence_of :name_profile, :profile_type, :gender
  validates :whatsapp, :telephone, presence: true, uniqueness: true


  enum gender: { masculine: "MASCULINO", feminine: "FEMININO" }
  enum profile_type: {
    adminstrador: "ADMINSTRADOR212", 
    funcionario: "FUNCIONARIO"
  }
  
  def self.find_by_user(user) 
    Profile.find_by(user_id: user.id)
  end
  
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :cities
    validates_presence_of :province_name
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_many :items
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :profile
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :profile, dependent: :destroy
  JOIN_CITIES_AND_PROVINCES = "JOIN cities ON cities.id = addresses.city_id JOIN provinces ON provinces.id = cities.province_id"
 
  has_one :user

  def self.find_user_by_house(house)
    User.joins(:profile)
        .joins("join profile_houses on profile_houses.profile_id = profiles.id")
        .where("profile_houses.house_id = #{house.id}")
        .take
  end

  def self.find_user_by_land(land)
    User.joins(:profile)
        .joins("join profile_lands on profile_lands.profile_id = profiles.id")
        .where("profile_lands.land_id = #{land.id}")
        .take
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  def add_cart
    @items = Item.all
  end
  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.profile ||= Profile.find_by_user(current_user)
    @item.price = @item.price + (@item.price * 0.14) #Teaxa do iva

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @item.profile ||= Profile.find_by_user(current_user)

    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:description, :manufacturing_date, :expiration_date, :quantity, :price, :tax, :item_code, :profite_value, :supplier_id, :category_id, :sector_id)
    end
end

app/helpers/cart_temps_helper.rb
module CartTempsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def add_new_item_to_cart_temp(item)
        cart = CartTemp.new
        cart.item = item
        cart
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/items/_form.html.erb
 <div class="container col-lg-10 my-4">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-body">

          <%= bootstrap_form_with(model: item) do |form| %>
            <% if item.errors.any? %>
              <div style="color: red">
                <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

                <ul>
                  <% item.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
              
              <%= form.text_field :description %>
              <%= form.date_field :manufacturing_date %>
              <%= form.date_field :expiration_date %>
              <%= form.number_field :quantity %>
              <span class="text-success">price = price + (price * 0.14)</span>  
              <%= form.number_field :price %>
              <%= form.number_field :profite_value %>
              <%= form.text_field :item_code %>
              <%= form.collection_select :supplier_id, Supplier.order(:name_supplier), :id, :name_supplier, 
              { label: Supplier.model_name.human(count: 1) }, 
              {class:"text-light-emphasis"} %> 
                <%= form.collection_select :category_id, Category.order(:name_category), :id, :name_category, 
              { label: Category.model_name.human(count: 1) }, 
              {class:"text-light-emphasis"} %> 

              <%= form.collection_select :sector_id, Sector.order(:name_sector), :id, :name_sector, 
              { label: Sector.model_name.human(count: 1) }, 
              {class:"text-light-emphasis"} %> 
             

              <div class="mb-3 d-grid gap-2">
                <%= form.submit class: "btn btn-info" %>
              </div>
          <% end %>

        </div>
      </div>
  </div>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
    <th scope="row"><%= item.item_code %></th>
    <td scope="col"><%= item.description %></td>
    <td scope="col"><%= item.quantity %></td>
    <td scope="col">14%</td>
    <td scope="col"><%= item.price %></td>
    <td scope="col"><%= item.category.name_category %></td>
    <td scope="col"><%= item.sector.name_sector %></td>
    <td scope="col">V.Pagar</td>
    <td scope="col"><%= item.profite_value %></td>
    <td scope="col"><%= item.profile.name_profile %></td>
    <td scope="col"><%= item.supplier.name_supplier %></td>
    <td scope="col"><%= item.created_at %></td>
    <td scope="col"><%= item.manufacturing_date %></td>
    <td scope="col"><%= item.expiration_date %></td>
    <td>
      <%= button_to "Destroy", item, method: :delete, class:"btn btn-danger btn-sm" %>
    </td>
    <td>
      <%= link_to "Edit", edit_item_path(item), class:"btn btn-success btn-sm" %>
    </td>
</div>

app/views/items/add_cart.html.erb
    
    <!-- Itens index-->
    <h5 class="fs-3 text-center">Add an item to cart</h5>

    <section>

      <div class="d-grid gap-2 my-1">
          <%= link_to "Continuar com a venda", cart_temps_path, class: "btn btn-warning"%> 
      </div>

      <table class="table table-hover shadow-sm">
          <thead>
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Nome/Descrição</th>
              <th scope="col">Q.Stock</th>
              <th scope="col">P.Unitário</th>
              <th scope="col">Categoria</th>
              <th scope="col">Sector</th>
              <th scope="col">V.Pagar</th>
              <th scope="col">Lucro</th>
              <th scope="col">D.Expiracao</th>
              <th scope="col">Adicionar</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
         
              <div id="items">
                <% @items.each do |item| %>
                   <tr>
                      <div id="<%= dom_id item %>">
                            <th scope="row"><%= item.item_code %></th>
                            <td scope="col"><%= item.description %></td>
                            <td scope="col"><%= item.quantity %></td>
                            <td scope="col"><%= item.price %></td>
                            <td scope="col"><%= item.category.name_category %></td>
                            <td scope="col"><%= item.sector.name_sector %></td>
                            <td scope="col"><%= item.price + item.profite_value%></td>
                            <td scope="col"><%= item.profite_value %></td>
                            <td scope="col"><%= item.expiration_date %></td>
                            <td>
                            <%= render "cart_temps/form", cart_temp: add_new_item_to_cart_temp(item) %>
                            </td>
                        </div>
                     </tr>
                <% end %>
              </div>
           
          </tbody>
        </table>

    </section>

    <!-- Fim Itens index-->

app/views/items/edit.html.erb
<h5 class="fs-3 text-center">Editing item</h5>
<%= render "form", item: @item %>

app/views/items/index.html.erb
    
    <!-- Itens index-->
    <h5 class="fs-3 text-center">Items</h5>

    <section>
      
      <div class="d-grid gap-2 my-1">
          <%= link_to "Continuar com a venda", cart_temps_path, class: "btn btn-warning"%> 
      </div>

      <table class="table table-hover shadow-sm">
          <thead>
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Nome/Descrição</th>
              <th scope="col">Q.Stock</th>
              <th scope="col">Taxa</th>
              <th scope="col">P.Unitário</th>
              <th scope="col">Categoria</th>
              <th scope="col">Sector</th>
              <th scope="col">V.Pagar</th>
              <th scope="col">Lucro</th>
              <th scope="col">Fornecedor</th>
              <th scope="col">Profile</th>
              <th scope="col">D.Cadastro</th>
              <th scope="col">D.Fabricação</th>
              <th scope="col">D.Expiracao</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
              <div id="items">
                <% @items.each do |item| %>
                 <tr>
                  <%= render item %>
                 </tr>
                <% end %>
              </div>
          </tbody>
        </table>

    </section>

    <!-- Fim Itens index-->

app/views/items/new.html.erb
<h5 class="fs-3 text-center">New item</h5>
<%= render "form", item: @item %>

app/views/items/show.html.erb
    
    <!-- Itens index-->
    <h5 class="fs-3 text-center">Item</h5>

    <section>

      <div class="d-grid gap-2 col-sm-15 my-1">
          <button class="btn btn-warning" type="button">Continuar com a venda</button>
      </div>

      <table class="table table-hover shadow-sm">
          <thead>
            <tr>
              <th scope="col">Código</th>
              <th scope="col">Nome/Descrição</th>
              <th scope="col">Q.Stock</th>
              <th scope="col">Taxa</th>
              <th scope="col">P.Unitário</th>
              <th scope="col">Categoria</th>
              <th scope="col">Sector</th>
              <th scope="col">V.Pagar</th>
              <th scope="col">Lucro</th>
              <th scope="col">Fornecedor</th>
              <th scope="col">Profile</th>
              <th scope="col">D.Cadastro</th>
              <th scope="col">D.Fabricação</th>
              <th scope="col">D.Expiracao</th>
              <th scope="col"></th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <%= render @item %>
            </tr>
          </tbody>
        </table>

    </section>

    <!-- Fim Itens index-->