config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :invoice_temps
  resources :cart_temps do 
    member do 
      get 'add_one_item'
      get 'remove_one_item'
    end

    collection do 
      get 'cart_abandoned'
    end
  end
  resources :items do 
    collection do 
      get 'add_cart'
    end 
  end 
  resources :categories
  resources :sectors
  resources :suppliers
  resources :profiles
  resources :cities, only: [:province] do 
    member do 
      get 'province'
    end
  end

  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    post '/users/sign_out', to: 'devise/sessions#destroy'
  end

  
  root "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city
  
  has_one :profile, dependent: :destroy
  has_one :supplier, dependent: :destroy
  has_one :company

  validates_presence_of :street, :city
end

app/models/cart_historic.rb
class CartHistoric < ApplicationRecord
  belongs_to :item
  has_many :invoice_temps

end

app/models/cart_temp.rb
class CartTemp < ApplicationRecord
  belongs_to :item
  validates :quantity, presence: true, comparison: { greater_than_or_equal_to: 1 } 

  
  def self.total_cost 
    CartTemp.joins("JOIN items ON items.id = cart_temps.item_id")
            .sum("price*cart_temps.quantity")
  end

  # SELECT sum(price) FROM cart_temps
	# JOIN items ON items.id = cart_temps.item_id;
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  has_many :address
  
  validates_presence_of :province, :city_name

  scope :find_cities, ->(province) { where(province_id: province.id)}
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_one_attached :image
end

app/models/invoice_temp.rb
class InvoiceTemp < ApplicationRecord
  belongs_to :profile
  belongs_to :cart_historic
 
  enum payment_method: { monetario: "MASCULINO", transferencia: "FEMININO", cartao_de_debito: "CARTAO_DEBITO"}

  def self.find_by_cart_historic(cart_historic)  
    InvoiceTemp.joins(:cart_historic)
              .where("cart_historics.code_cart = #{cart_historic.code_cart}")
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :supplier
  belongs_to :category
  belongs_to :profile
  belongs_to :sector

  has_many :cart_temps
  has_many :cart_historics

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :items
  has_many :invoice_temps

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [140, 140]
  end

  validates_presence_of :name_profile, :profile_type, :gender
  validates :whatsapp, :telephone, presence: true, uniqueness: true


  enum gender: { masculine: "MASCULINO", feminine: "FEMININO" }
  enum profile_type: {
    adminstrador: "ADMINSTRADOR212", 
    funcionario: "FUNCIONARIO"
  }
  
  def self.find_by_user(user) 
    Profile.find_by(user_id: user.id)
  end
  
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :cities
    validates_presence_of :province_name
end

app/models/sector.rb
class Sector < ApplicationRecord
    has_many :items
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :profile
  belongs_to :address
  accepts_nested_attributes_for :address, allow_destroy: true

  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :profile, dependent: :destroy
  JOIN_CITIES_AND_PROVINCES = "JOIN cities ON cities.id = addresses.city_id JOIN provinces ON provinces.id = cities.province_id"
 
  has_one :user

  def self.find_user_by_house(house)
    User.joins(:profile)
        .joins("join profile_houses on profile_houses.profile_id = profiles.id")
        .where("profile_houses.house_id = #{house.id}")
        .take
  end

  def self.find_user_by_land(land)
    User.joins(:profile)
        .joins("join profile_lands on profile_lands.profile_id = profiles.id")
        .where("profile_lands.land_id = #{land.id}")
        .take
  end
  
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def add_new_item_to_cart_temp(item)
        cart = CartTemp.new
        cart.item = item
        cart
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/_about.html.erb
  <section class="text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1>Bumbagora</h1>
        <p class="lead text-success">
Somos uma empresa angolana que nasceu em 2022, atuando na área de desenvolvimento de software, consultoria e vendas gerando valores para os nossos clientes. </p>
        <p>
        <% if !user_signed_in? %>    
          <div class="d-grid gap-2">
            <%= link_to "Criar conta", new_user_registration_path, class: "btn btn-outline-success my-2" %>
          </div>
        <% end %>
        </p>
      </div>
    </div>
  </section>

app/views/layouts/_alert.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light teal-darken-3">
  <p class="text-white text-center"> Conheça o CTO e CIO da empresa.</p>
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="https://twitter.com/PlusVicente"> 
          <i class="bi-twitter footer-icon"></i> 
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://github.com/Vicente-jpro"> 
          <i class="bi-github footer-icon"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="https://www.linkedin.com/in/vicente-sim%C3%A3o-504287160/"> 
          <i class="bi-linkedin text-white footer-icon"></i>
        </a>
      </li>
    </ul>
  </div>
  <p class="text-center text-white">
    ©2022 - Bumbagora | Direitos reservados
  </p>
</footer>

app/views/layouts/_header.html.erb
<!-- Slide bar -->
  <div class="flex-shrink-0 p-3 bg-white" style="width: 150px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold">venx</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#items-collapse" aria-expanded="true">
          Items
        </button>
        <div class="collapse show" id="items-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Novo</a></li>
            <li><a href="#" class="link-dark rounded">Listar</a></li>
            <li><a href="#" class="link-dark rounded">Editar</a></li>
            <li><a href="#" class="link-dark rounded">Mais vendidos</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#gestao-collapse" aria-expanded="true">
          Gestão
        </button>
        <div class="collapse show" id="gestao-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Lucro</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#fatura-collapse" aria-expanded="true">
          Fatura
        </button>
        <div class="collapse show" id="fatura-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Histórico</a></li>
            <li><a href="#" class="link-dark rounded">Guardadas</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#fornecedor-collapse" aria-expanded="true">
          Fornecedor
        </button>
        <div class="collapse show" id="fornecedor-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Novo</a></li>
            <li><a href="#" class="link-dark rounded">Listar</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <p><a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Canselar venda</a></p>

      </li>
      <li class="border-top my-3"></li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">New...</a></li>
            <li><a href="#" class="link-dark rounded">Profile</a></li>
            <li><a href="#" class="link-dark rounded">Settings</a></li>
            <li><a href="#" class="link-dark rounded">Sign out</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>

  <div class="b-example-divider"></div>

<!-- End Slide bar -->

  <!-- Nav bar-->
  <div class="container">
    <ul class="nav justify-content-end my-2">
      <li class="nav-item">
        <a class="nav-link active text-dark" aria-current="page" href="#">Painel de vendas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active text-dark" aria-current="page" href="#">Carrinho</a>
      </li>
      <li class="nav-item">
        <div class="mb-3">
          <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="Código do produto">
        </div>
      </li>
    </ul>
  </div>
  
  <!--End Nav bar-->

app/views/layouts/_info.html.erb
<br>
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
        <i class="bi-exclamation-circle-fill" ></i>
        <%= info %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_message.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-sm-9">
        <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <i class="bi-check-circle-fill" ></i>
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Nav bar -->
<% if user_signed_in? %>
  <ul class="nav justify-content-end my-2">
        <li class="nav-item">
      <%= link_to "Add itens to cart", add_cart_items_url, class: "nav-link active text-dark"%> 
    </li>

    <li class="nav-item">
      <%= link_to "Carrinho", cart_temps_path, class: "nav-link active text-dark"%> 
    </li>
    <li class="nav-item">
      <div class="mb-3">
        <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="Código do produto">
      </div>
    </li>
  </ul>
<% end %>
<!-- End Nav bar -->

app/views/layouts/_sidebar.html.erb
<!-- Slide bar -->
  <div class="flex-shrink-0 p-3 bg-white" style="width: 150px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold">venx</span>
    </a>
    <ul class="list-unstyled ps-0">

      <% if user_signed_in? %>

      <li class="mb-1">
        
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#items-collapse" aria-expanded="true">
          Items
        </button>
        <div class="collapse show" id="items-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li> 
            <%= link_to "Add to cart", add_cart_items_path, 
              class: "link-dark rounded"%> 
          </li>
           <li> 
            <%= link_to "New...", new_item_path, 
              class: "link-dark rounded"%> 
          </li>
            <li> 
            <%= link_to "List all", items_path, 
              class: "link-dark rounded"%> 
          </li>
            <li><a href="#" class="link-dark rounded">Mais vendidos</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#gestao-collapse" aria-expanded="true">
          Gestão
        </button>
        <div class="collapse show" id="gestao-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Lucro</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#fatura-collapse" aria-expanded="true">
          Fatura
        </button>
        <div class="collapse show" id="fatura-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Histórico</a></li>
            <li><a href="#" class="link-dark rounded">Guardadas</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#company-collapse" aria-expanded="true">
          Company
        </button>
        
        <div class="collapse show" id="company-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li> 
            <%= link_to "New...", new_company_path, 
              class: "link-dark rounded"%> 
          </li>
            <li> 
            <%= link_to "List all", companies_path, 
              class: "link-dark rounded"%> 
          </li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#category-collapse" aria-expanded="true">
          Category
        </button>
        
        <div class="collapse show" id="category-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li> 
            <%= link_to "New...", new_category_path, 
              class: "link-dark rounded"%> 
          </li>
            <li> 
            <%= link_to "List all", categories_path, 
              class: "link-dark rounded"%> 
          </li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#sector-collapse" aria-expanded="true">
          Sector
        </button>
        
        <div class="collapse show" id="sector-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li> 
            <%= link_to "New...", new_sector_path, 
              class: "link-dark rounded"%> 
          </li>
            <li> 
            <%= link_to "List all", sectors_path, 
              class: "link-dark rounded"%> 
          </li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#fornecedor-collapse" aria-expanded="true">
          Fornecedor
        </button>
        
        <div class="collapse show" id="fornecedor-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <li> 
            <%= link_to "new...", new_supplier_path, 
              class: "link-dark rounded"%> 
          </li>
            <li> 
            <%= link_to "List all", suppliers_path, 
              class: "link-dark rounded"%> 
          </li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <p><a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Canselar venda</a></p>

      </li>
      <li class="border-top my-3"></li>

      <% end %>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
          <% if user_signed_in? %>
             <li> <%= link_to t("navbar.profile"), new_profile_path, 
             class: "link-dark rounded"%> </li>
            <li> 
              <%= link_to t("navbar.security"), edit_user_registration_path, 
              class: "link-dark rounded"%> 
            </li>
            <li> 
              <%= link_to t("devise.links.logout"), destroy_user_session_path,  method: :delete, 
                class: "link-dark rounded" %> 
            </li>
          <% end %>
      
          <% if !user_signed_in? %>
            
            <li> <%= link_to t("devise.links.sign.in"), user_session_path, class: "link-dark rounded" %> </li>
         
          <% end %>
          
            <%= link_to t("devise.links.sign.up"), new_user_registration_path, class: "link-dark rounded" if !user_signed_in?%> 
      
          </ul>
        </div>
      </li>
    </ul>
  </div>

  <div class="b-example-divider"></div>

<!-- End Slide bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <% cache do %> 
        <%= render 'layouts/sidebar' %>
      <% end %> 

      <div class="container">
        <% cache do %> 
          <%= render 'layouts/navbar' %>
        <% end %> 

        <%= render 'layouts/info' if info %>
        <%= render 'layouts/message' if notice %>
        <%= render 'layouts/alert' if alert %> 
  
        <%= yield %>
      </div>
     </main>
    
  </body>
</html>